# prometheus.sh - metrics access for the audit.  Sourced by init.sh.
#
# Two separate Prometheus instances are involved, and they answer different questions:
#
#   1. CLUSTER monitoring  - cAdvisor, kubelet, kube-state-metrics.
#                            Needed by guides 04, 06, 07, 08, 09.
#                            Helpers: tq (instant), tqr (range)
#   2. K10's own Prometheus - only scrapes K10 services. No cAdvisor at all.
#                            Needed by guides 02, 03, 09, 11, 13.
#                            Helpers: kq (instant), reached via a port-forward
#
# ---------------------------------------------------------------------------
# CLUSTER MONITORING - the default below assumes OpenShift
# ---------------------------------------------------------------------------
# On OpenShift, cluster monitoring is enabled out of the box and exposed through the
# thanos-querier route. A short-lived token is minted from the prometheus-k8s service
# account, which already holds cluster-wide metrics read access.
#
# NOT ON OPENSHIFT? Do not edit this file. Instead export PROM_URL (and optionally
# PROM_TOKEN) BEFORE sourcing init.sh, and everything below is skipped:
#
#   # vanilla kube-prometheus-stack, reached over a port-forward
#   kubectl -n monitoring port-forward svc/prometheus-operated 19091:9090 &
#   export PROM_URL=http://localhost:19091
#   . lib/init.sh
#
#   # Prometheus behind an ingress with a bearer token
#   export PROM_URL=https://prometheus.example.com
#   export PROM_TOKEN=$(cat ~/.prom-token)
#   . lib/init.sh
#
#   # Grafana Mimir / Thanos needing a tenant header
#   export PROM_URL=https://mimir.example.com/prometheus
#   export PROM_HEADER='X-Scope-OrgID: prod'
#   . lib/init.sh

PROM_NS=${PROM_NS:-openshift-monitoring}
PROM_SA=${PROM_SA:-prometheus-k8s}
PROM_TOKEN_TTL=${PROM_TOKEN_TTL:-6h}

# Mint or re-mint the cluster monitoring token. The OpenShift token is short lived,
# so call this again if queries start returning Unauthorized.
prom_token_refresh() {
  if [ -n "${PROM_URL_IS_CUSTOM:-}" ] && [ -z "${PROM_TOKEN:-}" ]; then
    return 0
  fi
  PROM_TOKEN=$(kubectl -n "$PROM_NS" create token "$PROM_SA" --duration="$PROM_TOKEN_TTL" 2>/dev/null)
  if [ -z "$PROM_TOKEN" ]; then
    echo "prom_token_refresh: could not mint a token for $PROM_SA in $PROM_NS" >&2
    return 1
  fi
  export PROM_TOKEN
  # kept for readability in the guides and in the provenance record
  export THANOS_TOKEN="$PROM_TOKEN"
  _prom_write_conf
  return 0
}

# Credentials and headers go into a curl config file rather than into shell variables
# that get expanded on the command line. Two reasons:
#   - ${VAR:+-H "..."} word-splits in bash but NOT in zsh, where it collapses into a
#     single argument and curl silently sends no auth header;
#   - the bearer token never appears in the process list.
_prom_write_conf() {
  if [ -z "${PROM_CURL_CONF:-}" ] || [ ! -f "${PROM_CURL_CONF:-}" ]; then
    PROM_CURL_CONF=$(mktemp)
    export PROM_CURL_CONF
  fi
  chmod 600 "$PROM_CURL_CONF" 2>/dev/null
  {
    echo 'silent'
    echo 'insecure'
    [ -n "${PROM_TOKEN:-}" ]  && echo "header = \"Authorization: Bearer $PROM_TOKEN\""
    [ -n "${PROM_HEADER:-}" ] && echo "header = \"$PROM_HEADER\""
  } > "$PROM_CURL_CONF"
}

prom_init() {
  if [ -n "${PROM_URL:-}" ]; then
    # caller configured a non-OpenShift Prometheus
    export PROM_URL_IS_CUSTOM=1
    export PROM_URL
    export THANOS_HOST="${PROM_URL#*://}"
    _prom_write_conf
    return 0
  fi

  _prom_host=$(kubectl -n "$PROM_NS" get route thanos-querier -o jsonpath='{.spec.host}' 2>/dev/null)
  if [ -z "$_prom_host" ]; then
    echo "prom_init: no thanos-querier route in $PROM_NS." >&2
    echo "prom_init: not OpenShift? export PROM_URL before sourcing init.sh - see lib/prometheus.sh" >&2
    return 1
  fi
  export THANOS_HOST="$_prom_host"
  export PROM_URL="https://$_prom_host"
  prom_token_refresh || return 1
  return 0
}

# Refuse to run in a session where lib/init.sh did not complete (for example because
# the authorisation gate failed). Prevents a script from blundering on after a failed
# source, which "return" alone cannot prevent.
_audit_ready() {
  if [ "${AUDIT_READY:-no}" != "yes" ]; then
    echo "${1:-this command}: audit session is not ready - lib/init.sh did not complete." >&2
    echo "  Re-source it and fix what it reports (likely a missing permission)." >&2
    return 1
  fi
  return 0
}

# _prom_fetch <url> [curl args...]
# One place that actually talks to Prometheus, so every caller gets the same handling
# of the two failure modes that otherwise surface as "jq: parse error: Invalid numeric
# literal at line 2, column 0":
#   - the metrics token expired (it is short lived by design), or
#   - the mode-0600 curl config in $TMPDIR was reaped by the OS, so curl sent no
#     Authorization header at all.
# Both return the bare string "Unauthorized", which is not JSON. Re-mint once and retry;
# if it still fails, say so on stderr and return non-zero rather than emitting a body
# that breaks the caller's jq.
_prom_fetch() {
  _audit_ready "${_PROM_CALLER:-prometheus query}" || return 1
  [ -f "${PROM_CURL_CONF:-}" ] || _prom_write_conf

  _pf_body=$(mktemp)
  _pf_code=$(curl -K "$PROM_CURL_CONF" -s -o "$_pf_body" -w '%{http_code}' "$@" 2>/dev/null)

  if [ "$_pf_code" = "401" ] || [ "$_pf_code" = "403" ] || ! head -c 1 "$_pf_body" 2>/dev/null | grep -q '{'; then
    if prom_token_refresh >/dev/null 2>&1; then
      _pf_code=$(curl -K "$PROM_CURL_CONF" -s -o "$_pf_body" -w '%{http_code}' "$@" 2>/dev/null)
    fi
  fi

  if [ "$_pf_code" != "200" ] || ! head -c 1 "$_pf_body" 2>/dev/null | grep -q '{'; then
    echo "${_PROM_CALLER:-prometheus}: query failed (HTTP ${_pf_code:-?}) against $PROM_URL" >&2
    sed -n '1,3p' "$_pf_body" 2>/dev/null | sed 's/^/  /' >&2
    echo "  try: prom_token_refresh   (or re-source lib/init.sh)" >&2
    rm -f "$_pf_body"
    return 1
  fi

  cat "$_pf_body"
  rm -f "$_pf_body"
}

# tq QUERY                         instant query
tq() {
  _PROM_CALLER=tq _prom_fetch "$PROM_URL/api/v1/query" \
    --data-urlencode "query=$1"
}

# tqr QUERY START_EPOCH END_EPOCH [STEP]        range query
tqr() {
  _PROM_CALLER=tqr _prom_fetch "$PROM_URL/api/v1/query_range" \
    --data-urlencode "query=$1" \
    --data-urlencode "start=$2" \
    --data-urlencode "end=$3" \
    --data-urlencode "step=${4:-30s}"
}

# tq_scalar '<promql>'    just the value of a single-series query, or empty
tq_scalar() {
  tq "$1" | jq -r '.data.result[0].value[1] // empty'
}

# prom_check   verify the cluster monitoring path end to end
prom_check() {
  _r=$(tq_scalar "count(container_cpu_usage_seconds_total{namespace=\"${K10NS:-kasten-io}\"})")
  if [ -z "$_r" ]; then
    echo "prom_check: FAIL - reachable but no cAdvisor series for namespace ${K10NS:-kasten-io}," >&2
    echo "prom_check: or the token was rejected. Try prom_token_refresh." >&2
    return 1
  fi
  echo "prom_check: OK - $_r cAdvisor series for ${K10NS:-kasten-io}"
  return 0
}

# ---------------------------------------------------------------------------
# K10's own Prometheus
# ---------------------------------------------------------------------------
# Served under the /k10/prometheus prefix, not at the root. Reached by port-forward.

K10PROM_PORT=${K10PROM_PORT:-19090}

k10prom_start() {
  pf_start prometheus-server "$K10PROM_PORT:80" || return 1
  export K10PROM="http://localhost:$K10PROM_PORT/k10/prometheus/api/v1"
  K10PROM_PF_PID=$PF_PID
  return 0
}

k10prom_stop() {
  if [ -n "${K10PROM_PF_PID:-}" ]; then
    kill "$K10PROM_PF_PID" 2>/dev/null
    wait "$K10PROM_PF_PID" 2>/dev/null
    K10PROM_PF_PID=""
  fi
}

# kq '<promql>'   instant query against K10's own Prometheus
# Reached over a port-forward, so the failure mode is a dead forward rather than an
# expired token: curl then returns nothing, and the caller's jq reports
# "Invalid numeric literal". Detect it and say which forward to restart.
kq() {
  _audit_ready kq || return 1
  if [ -z "${K10PROM:-}" ]; then
    echo "kq: no forward to K10 Prometheus - run k10prom_start first" >&2
    return 1
  fi
  _kq_body=$(mktemp)
  _kq_code=$(curl -s -o "$_kq_body" -w '%{http_code}' \
               "$K10PROM/query" --data-urlencode "query=$1" 2>/dev/null)
  if [ "$_kq_code" != "200" ] || ! head -c 1 "$_kq_body" 2>/dev/null | grep -q '{'; then
    echo "kq: query failed (HTTP ${_kq_code:-?}) against $K10PROM" >&2
    if [ -n "${K10PROM_PF_PID:-}" ] && ! kill -0 "$K10PROM_PF_PID" 2>/dev/null; then
      echo "  the port-forward has died - run k10prom_start again" >&2
    else
      echo "  check the forward is up: k10prom_check" >&2
    fi
    sed -n '1,3p' "$_kq_body" 2>/dev/null | sed 's/^/  /' >&2
    rm -f "$_kq_body"
    return 1
  fi
  cat "$_kq_body"
  rm -f "$_kq_body"
}

kq_scalar() {
  kq "$1" | jq -r '.data.result[0].value[1] // empty'
}

k10prom_check() {
  _v=$(curl -s "${K10PROM%/api/v1}/api/v1/status/buildinfo" 2>/dev/null | jq -r '.data.version // empty')
  if [ -z "$_v" ]; then
    echo "k10prom_check: FAIL - forward down, or the /k10/prometheus prefix was dropped" >&2
    return 1
  fi
  echo "k10prom_check: OK - K10 Prometheus $_v"
  return 0
}
